language: java
jdk:
  - oraclejdk11
install: true
sudo: false
notifications:
  email: false
script:
  - ./gradlew clean build -x signArchives --console=plain
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
after_success:
- bash <(curl -s https://codecov.io/bash)
